trigger:
  branches:
    include:
      - main

name: $(Date:yyyyMMdd)$(Rev:rrr)

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
      npm version 1.0.$(Build.BuildNumber) --no-git-tag-version --allow-same-version
    displayName: "Install dependencies and build"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)"
      Contents: "README.md"
      TargetFolder: "$(Build.ArtifactStagingDirectory)/build"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)"
      Contents: "LICENSE"
      TargetFolder: "$(Build.ArtifactStagingDirectory)/build"

  - task: Npm@1
    inputs:
      command: publish
      publishRegistry: useExternalRegistry
      publishEndpoint: "NPM"
